# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

#pool:
#  vmImage: 'windows-latest'
pool: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
    
- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'http://10.229.222.183:8999/scancentral-ctrl/'
    scanCentralClientToken: '$(ScanCentral.ClientToken)'
    sscUrl: 'http://10.229.222.183:8180/ssc/'
    sscCiToken: '$(ScanCentral.SscCiToken)'
    uploadToSSC: true
    applicationName: 'WebGoat.NET'
    applicationVersion: '1'
    buildFailureCriteria: '[fortify priority order]:critical'
    taskResultForBuildFailureCriteria: 'FAIL'
    buildTool: 'msbuild'
    buildFile: 'WebGoat.Net.sln'
    block: true
    outputFile: 'results.fpr'
    
#- task: FortifyOnDemandStatic@8
#  env:
#    PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\;$env:PATH
#  inputs:
#    FortifyProjects: '.'
#    FodConnection: 'FoD-AMS-W'
#    ReleaseOptions: '0'
#    ReleaseId: 295892
#    EntitlementSelection: '1'
#    EntitlementPreference: '1'
#    OverrideScanSettings: '2'
#    InProgressScanActionType: '2'
#    RemediationScanPreference: '2'
#    BuildType: 'msbuild'
#    BuildFile: 'WebGoat.Net.sln'
#    PolicyFailAction: '0'

#- task: FortifyOnDemandStatic@8
#  inputs:
#    FortifyProjects: '.'
#    FodConnection: 'FoD-AMS-W'
#    ReleaseOptions: '0'
#    ReleaseId: 295892
#    EntitlementSelection: '1'
#    EntitlementPreference: '3'
#    OverrideScanSettings: '2'
#    InProgressScanActionType: '2'
#    RemediationScanPreference: '2'
#    BuildType: 'msbuild'
#    BuildFile: 'WebGoat.Net.sln'

#    PolicyFailAction: '0'

#- task: PowerShell@2
#  inputs:
#    targetType: 'inline'
#    script: |
#      echo Running:
#      echo "Get-Content $env:LocalAppData\Fortify\scancentral-21.1.2\log\scancentral.log"
#      Get-Content $env:LocalAppData\Fortify\scancentral-21.1.2\log\scancentral.log